### ISSUE TITLE
System.MissingMethodException: Method not found ...

### ISSUE THREAD

**Issue by afparsons** [adamradocz/boinc-manager#5]
This looks like an interesting project! I'd love to try it out. Maybe I've done something wrong or missed a step in the documentation. 

**Date:** 27 April 2020

**OS:** Ubuntu Server 20.04 LTS on Proxmox 6.1.

Docker version 19.03.8, build afacb8b7f0

```
$ sudo docker run --name boinc-manager-web -p "8100:80" -v /opt/appdata/boinc-manager-web:/app/BoincManager adamradocz/boinc-manager-web
```
Note the change from port 8000 to 8100. I've also tried the docker-compose file. 

```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {f724085f-1a24-4e01-b601-7ca1789fe838} may be persisted to storage in unencrypted form.
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0> Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder.CreateTable(System.String, System.Func`2<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.ColumnsBuilder,!!0>, System.String, System.Action`1<Microsoft.EntityFrameworkCore.Migrations.Operations.Builders.CreateTableBuilder`1<!!0>>)'.
   at BoincManager.Migrations.InitialCreate.Up(MigrationBuilder migrationBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
   at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass15_2.<GetMigrationCommandLists>b__2()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at BoincManager.Utils.InitializeApplication(ApplicationDbContext context, Manager manager, Boolean useObservableCollections) in /src/BoincManager/Utils.cs:line 31
   at BoincManagerWeb.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ApplicationDbContext context, Manager manager) in /src/BoincManagerWeb/Startup.cs:line 100
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BoincManager.Manager.Dispose(Boolean disposing) in /src/BoincManager/Manager.cs:line 663
   at BoincManager.Manager.Dispose() in /src/BoincManager/Manager.cs:line 640
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BoincManagerWeb.Program.Main(String[] args) in /src/BoincManagerWeb/Program.cs:line 17
```

I have no experience with dotnet or C#, so I don't exactly know where to start looking.

**Comment by adamradocz** [comment]
I updated the packages, it should work now.
Please check it again.

**Comment by afparsons** [comment]
It works! I've been able to use the web client to connect to my local instance. Thank you for the quick turnaround. I will close this and mark it as resolved.

---
I do, however, have a tangential question.

Is it correct that the web client functions only as a "viewer"? I was unable to figure out how log in and _add_ a project (Rosetta) via the web client, but have instead done so through the desktop version of Boinc Manager (Linux). I can _view_ the task progress via the browser.

**Comment by adamradocz** [comment]
Currently, you can only view and not edit. If I have more time, I'll add extra functionality.
The progress bar should work. It needs permission to run javascript.
